### ISSUE TITLE
Crash removing entity from module in editor mode

### ISSUE THREAD

**Issue by Danielv123** [Danielv123/factory_modules#1]
![Yeah](https://cdn.discordapp.com/attachments/912850585273892864/961545913409605682/unknown.png)

**Comment by n0t49a1n** [comment]
Editor mode also doesnt trigger  the module frame when u paste down wall in bulk. Single placement is fine

**Comment by Danielv123** [comment]
Does this happen when right click removing entities or only when bulk removing?

**Comment by n0t49a1n** [comment]
Right click

**Comment by Danielv123** [comment]
I can no longer reproduce this. Feel free to reopen if you can find a way to do it in 0.3+
